### ISSUE TITLE
Remove Heroku Redis add-on

### ISSUE THREAD

**Issue by garyhtou** [hackclub/airbridge#98]
From a quick glance, I think this codebase [no longer needs Redis](https://github.com/hackclub/airbridge/commit/8688edd4f428de3f017dc9447c79c34b7719659d). However, on Heroku, we still have a Heroku Key-Value Store Mini add-on. It might be good to delete.

https://dashboard.heroku.com/apps/api2-hackclub

https://dashboard.heroku.com/apps/api2-hackclub/datastores/101e70da-160c-4f5b-b36e-6b8ebdf8eef1

**Comment by maxwofford** [comment]
Just removed from prod!
